import type { LanguageMode } from "../types";

const esDictionary: Record<string, string> = {
  "Cyber risk": "Riesgo cibernético",
  ISMS: "SGSI",
  Payments: "Pagos",
  Trust: "Confianza",
  Privacy: "Privacidad",
  Controls: "Controles",
  "Adversary behavior": "Comportamiento adversario",
  "Defensive countermeasures": "Contramedidas defensivas",
  "AI system risk": "Riesgo de sistemas de IA",
  "Fraud behavior": "Comportamiento de fraude",
  Governance: "Gobierno",
  Govern: "Gobernar",
  Identify: "Identificar",
  Protect: "Proteger",
  Detect: "Detectar",
  Respond: "Responder",
  Recover: "Recuperar",
  Context: "Contexto",
  Leadership: "Liderazgo",
  Risk: "Riesgo",
  Improvement: "Mejora",
  Network: "Red",
  Data: "Datos",
  Access: "Acceso",
  Monitoring: "Monitoreo",
  Testing: "Pruebas",
  Security: "Seguridad",
  Availability: "Disponibilidad",
  Confidentiality: "Confidencialidad",
  Lawfulness: "Licitud",
  "Data rights": "Derechos de datos",
  "Breach response": "Respuesta a brechas",
  Inventory: "Inventario",
  Hardening: "Endurecimiento",
  Logging: "Registro",
  Response: "Respuesta",
  "Initial access": "Acceso inicial",
  Execution: "Ejecución",
  Persistence: "Persistencia",
  Impact: "Impacto",
  Harden: "Endurecer",
  Isolate: "Aislar",
  Evict: "Expulsar",
  Restore: "Restaurar",
  Model: "Modelo",
  Agent: "Agente",
  Prompt: "Prompt",
  "Supply chain": "Cadena de suministro",
  Reconnaissance: "Reconocimiento",
  "Resource development": "Desarrollo de recursos",
  Stealth: "Ocultamiento",
  "Defense impairment": "Deterioro de defensas",
  Positioning: "Posicionamiento",
  Monetization: "Monetización",
  Evaluate: "Evaluar",
  Align: "Alinear",
  Build: "Construir",
  Deliver: "Entregar",
  Monitor: "Monitorear",
  "No active evidence": "Sin evidencia activa",
  "Asset visibility": "Visibilidad de activos",
  Detection: "Detección",
  Recovery: "Recuperación",
  "Governance ownership": "Responsabilidad de gobierno",
  "External exposure inventory": "Inventario de exposición externa",
  "Detection coverage": "Cobertura de detección",
  "Response playbooks": "Playbooks de respuesta",
  "KEV/CVE evidence": "Evidencia KEV/CVE",
  "risk findings": "hallazgos de riesgo",
  "source health": "salud de fuentes",
  "incident response maturity": "madurez de respuesta a incidentes",
  "Risk treatment": "Tratamiento de riesgo",
  "supplier control": "control de proveedores",
  "access control": "control de acceso",
  "monitoring evidence": "evidencia de monitoreo",
  "control maturity": "madurez de controles",
  "findings evidence": "evidencia de hallazgos",
  "supplier/open web signals": "señales de proveedores/web abierta",
  recommendations: "recomendaciones",
  "Cardholder data exposure": "Exposición de datos de tarjetahabiente",
  "payment fraud": "fraude de pagos",
  "credential access": "acceso a credenciales",
  "security testing": "pruebas de seguridad",
  "fraud signals": "señales de fraude",
  "phishing records": "registros de phishing",
  "ATO mentions": "menciones de toma de cuentas",
  "external payment surface": "superficie externa de pagos",
  "Trust service criteria": "Criterios de servicios de confianza",
  "availability exposure": "exposición de disponibilidad",
  "confidentiality impact": "impacto en confidencialidad",
  "privacy control evidence": "evidencia de controles de privacidad",
  "source reliability": "confiabilidad de fuente",
  "identity abuse": "abuso de identidad",
  "service disruption": "interrupción de servicio",
  "data handling signals": "señales de tratamiento de datos",
  "Personal data exposure": "Exposición de datos personales",
  "breach notification": "notificación de brecha",
  "processor control": "control de encargados",
  "data subject impact": "impacto en titulares de datos",
  "Breach notification": "Notificación de brecha",
  "leak indicators": "indicadores de filtración",
  "privacy mentions": "menciones de privacidad",
  "phishing/social engineering": "phishing/ingeniería social",
  "breach-source records": "registros de fuentes de brecha",
  "Asset inventory": "Inventario de activos",
  "secure configuration": "configuración segura",
  "patch priority": "prioridad de parches",
  "logging and response": "registro y respuesta",
  "CVE/KEV signals": "señales CVE/KEV",
  "exploit patterns": "patrones de explotación",
  "control score": "puntaje de control",
  "residual risk": "riesgo residual",
  "Observed tactics": "Tácticas observadas",
  "mapped techniques": "técnicas mapeadas",
  "coverage gaps": "brechas de cobertura",
  "example evidence": "evidencia de ejemplo",
  technique_counts: "conteo de técnicas",
  "tactic coverage": "cobertura de tácticas",
  "event technique": "técnica del evento",
  "source examples": "ejemplos de fuente",
  "Countermeasure fit": "Ajuste de contramedidas",
  "defensive tooling": "herramientas defensivas",
  "response action": "acción de respuesta",
  "control uplift": "mejora de controles",
  "D3FEND rows": "filas D3FEND",
  "ATT&CK mapped techniques": "técnicas ATT&CK mapeadas",
  samples: "muestras",
  "recommended actions": "acciones recomendadas",
  "AI asset exposure": "exposición de activos de IA",
  "prompt handling": "manejo de prompts",
  "model supply chain": "cadena de suministro del modelo",
  "agent autonomy": "autonomía de agentes",
  "AI/LLM matched signals": "señales IA/LLM coincidentes",
  "ATLAS sections": "secciones ATLAS",
  "automation mentions": "menciones de automatización",
  "supply-chain records": "registros de cadena de suministro",
  "Fraud actor behavior": "Comportamiento del actor de fraude",
  "identity and transaction abuse": "abuso de identidad y transacciones",
  "impersonation infrastructure": "infraestructura de suplantación",
  "monetization path": "ruta de monetización",
  "explicit F3 mappings": "mapeos F3 explícitos",
  "assured current-run records": "registros verificados de la corrida actual",
  "fraud and brand evidence": "evidencia de fraude y marca",
  "identity abuse signals": "señales de abuso de identidad",
  "Decision rights": "Derechos de decisión",
  "risk ownership": "responsabilidad de riesgo",
  "performance monitoring": "monitoreo de desempeño",
  "assurance evidence": "evidencia de aseguramiento",
  "strategic risk": "riesgo estratégico",
  "governance signals": "señales de gobierno",
  "source coverage": "cobertura de fuentes",
  vulnerability: "vulnerabilidad",
  "open web": "web abierta",
  Evidence: "Evidencia",
  "Supplier control": "Control de proveedores",
  "Access control": "Control de acceso",
  "Cardholder data": "Datos de tarjetahabiente",
  "Vulnerability management": "Gestión de vulnerabilidades",
  "Processing integrity": "Integridad de procesamiento",
  "Personal data": "Datos personales",
  "Lawful basis": "Base legal",
  "Data subject rights": "Derechos del titular",
  "Processor control": "Control del encargado",
  "Secure configuration": "Configuración segura",
  "Malware defenses": "Defensas contra malware",
  "Incident response": "Respuesta a incidentes",
  "Credential access": "Acceso a credenciales",
  "Detection engineering": "Ingeniería de detección",
  "Recovery controls": "Controles de recuperación",
  "AI model exposure": "Exposición de modelos de IA",
  "Training data": "Datos de entrenamiento",
  "Agent autonomy": "Autonomía de agentes",
  "AI supply chain": "Cadena de suministro de IA",
  "Risk ownership": "Responsabilidad del riesgo",
  Performance: "Desempeño",
  Assurance: "Aseguramiento",
  "Immediate executive attention": "Atención ejecutiva inmediata",
  "Prioritize control uplift": "Priorizar mejora de controles",
  "Track and validate": "Dar seguimiento y validar",
  "Prioritize executive cyber risk decisions across govern, protect, detect, respond and recover functions.":
    "Prioriza decisiones ejecutivas de riesgo cibernético en gobierno, protección, detección, respuesta y recuperación.",
  "Translate threat intelligence into ISMS control gaps, evidence needs and treatment priorities.":
    "Traduce la inteligencia de amenazas en brechas del SGSI, necesidades de evidencia y prioridades de tratamiento.",
  "Identify payment-control impact when threat signals touch channels, accounts or customer data.":
    "Identifica impacto en controles de pago cuando las señales afectan canales, cuentas o datos de clientes.",
  "Connect intelligence findings to trust criteria that matter for assurance and customer confidence.":
    "Conecta hallazgos de inteligencia con criterios de confianza relevantes para aseguramiento y confianza del cliente.",
  "Surface privacy and breach-response implications when open-source or dark-web evidence touches personal data.":
    "Expone implicaciones de privacidad y respuesta a brechas cuando la evidencia abierta o dark web toca datos personales.",
  "Convert threat activity into concrete safeguard priorities for hardening, monitoring and response.":
    "Convierte actividad de amenaza en prioridades concretas de salvaguardas para endurecimiento, monitoreo y respuesta.",
  "Explain what adversary behavior is visible so detection and response can be prioritized by technique.":
    "Explica qué comportamiento adversario es visible para priorizar detección y respuesta por técnica.",
  "Translate observed ATT&CK techniques into defensive actions and tool families.":
    "Traduce técnicas ATT&CK observadas en acciones defensivas y familias de herramientas.",
  "Review AI and automation risk only when explicit AI/model/agent/prompt signals are present.":
    "Revisa riesgo de IA y automatización solo cuando existen señales explícitas de IA, modelo, agente o prompt.",
  "Map assured fraud-related evidence to official F3 tactics and techniques without treating a behavioral match as a confirmed fraud incident.":
    "Relaciona evidencia verificada de fraude con tácticas y técnicas oficiales de F3, sin presentar una coincidencia de comportamiento como un incidente de fraude confirmado.",
  "Support board-level governance decisions by connecting intelligence signals to ownership and assurance.":
    "Apoya decisiones de gobierno directivo conectando señales de inteligencia con responsables y aseguramiento."
};

export function localizeFrameworkText(value: string, language: LanguageMode): string {
  if (language === "en") return value;
  return esDictionary[value] ?? value;
}

export function localizeFrameworkList(values: string[], language: LanguageMode): string[] {
  return values.map((value) => localizeFrameworkText(value, language));
}
