import { AlertTriangle, KeyRound, LockKeyhole, Moon, ShieldCheck, Sun, UserRound } from "lucide-react";
import type { FormEvent } from "react";
import { useState } from "react";
import { authenticateUser, hashPassword, lockoutMinutes, verifyMfaCode } from "../data/auth";
import type { LanguageMode, LocalUser, ThemeMode } from "../types";

interface LoginViewProps {
  users: LocalUser[];
  language: LanguageMode;
  theme: ThemeMode;
  onLanguageChange: (language: LanguageMode) => void;
  onThemeChange: (theme: ThemeMode) => void;
  onLogin: (user: LocalUser) => void;
  onUsersChange: (users: LocalUser[]) => void;
  sessionMessage?: string | null;
}

const copy = {
  es: {
    eyebrow: "CyberDecisionEngine",
    title: "Ciberinteligencia accionable para decisión inmediata",
    subtitle: "Ingreso local con roles para administrar fuentes, generar análisis y consultar tableros ejecutivos.",
    username: "Usuario",
    password: "Contraseña",
    mfa: "Código de doble factor",
    submit: "Ingresar",
    verify: "Validar acceso",
    error: "Usuario o contraseña inválida.",
    missingUsername: "Ingresa el usuario para identificar la cuenta.",
    missingPassword: "Ingresa la contraseña para validar la identidad.",
    missingMfa: "Ingresa el código temporal MFA generado por un administrador.",
    mfaRequired: "La contraseña es correcta. Esta cuenta requiere doble factor.",
    mfaExpired: "El código MFA expiró. Solicita uno nuevo en Configuración.",
    invalidMfa: "Código MFA inválido.",
    changeRequired: "Debes cambiar la contraseña temporal antes de ingresar.",
    newPassword: "Nueva contraseña",
    confirmPassword: "Confirmar contraseña",
    updateAndEnter: "Actualizar y entrar",
    weakPassword: "La nueva contraseña debe tener al menos 12 caracteres.",
    mismatch: "La nueva contraseña y su confirmación no coinciden.",
    locked: "Cuenta bloqueada por intentos fallidos. Espera {minutes} min o solicita desbloqueo al admin.",
    invalidWithAttempts: "Credenciales inválidas. Intentos fallidos: {attempts}/5.",
    model: "Modelo diseñado por Edwin Peñuela",
    posture: "Uso defensivo, pasivo, autorizado y trazable.",
    roles: "Administrador / Analista / Directivo",
    governance: "Permisos locales, usuarios y gobierno de conectores API.",
    guidance: "Guía de acceso",
    why: "Qué falta y por qué",
    languageTitle: "Idioma",
    themeTitle: "Tema"
  },
  en: {
    eyebrow: "CyberDecisionEngine",
    title: "Actionable cyber intelligence for immediate decisions",
    subtitle: "Local role-based access to manage sources, generate analysis and read executive dashboards.",
    username: "Username",
    password: "Password",
    mfa: "Two-factor code",
    submit: "Sign in",
    verify: "Verify access",
    error: "Invalid username or password.",
    missingUsername: "Enter the username to identify the account.",
    missingPassword: "Enter the password to validate identity.",
    missingMfa: "Enter the temporary MFA code generated by an administrator.",
    mfaRequired: "Password accepted. This account requires two-factor verification.",
    mfaExpired: "The MFA code expired. Request a new one in Settings.",
    invalidMfa: "Invalid MFA code.",
    changeRequired: "You must change the temporary password before entering.",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    updateAndEnter: "Update and enter",
    weakPassword: "New password must be at least 12 characters.",
    mismatch: "New password and confirmation do not match.",
    locked: "Account locked after failed attempts. Wait {minutes} min or request admin unlock.",
    invalidWithAttempts: "Invalid credentials. Failed attempts: {attempts}/5.",
    model: "Model designed by Edwin Penuela",
    posture: "Defensive, passive, authorized and traceable use.",
    roles: "Admin / Analyst / Executive",
    governance: "Local permissions, users and API connector governance.",
    guidance: "Access guidance",
    why: "What is missing and why",
    languageTitle: "Language",
    themeTitle: "Theme"
  }
};

type FieldErrors = Partial<Record<"username" | "password" | "mfa", string>>;

export function LoginView({
  users,
  language,
  theme,
  onLanguageChange,
  onThemeChange,
  onLogin,
  onUsersChange,
  sessionMessage
}: LoginViewProps) {
  const [username, setUsername] = useState("admin");
  const [password, setPassword] = useState("");
  const [mfaCode, setMfaCode] = useState("");
  const [pendingUser, setPendingUser] = useState<LocalUser | null>(null);
  const [passwordChangeUser, setPasswordChangeUser] = useState<LocalUser | null>(null);
  const [passwordChangeDraft, setPasswordChangeDraft] = useState({ next: "", confirm: "" });
  const [error, setError] = useState<string | null>(null);
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const labels = copy[language];

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (passwordChangeUser) {
      await submitPasswordChange();
      return;
    }
    if (pendingUser) {
      await submitMfa();
      return;
    }
    const nextErrors: FieldErrors = {};
    if (!username.trim()) nextErrors.username = labels.missingUsername;
    if (!password.trim()) nextErrors.password = labels.missingPassword;
    setFieldErrors(nextErrors);
    if (Object.keys(nextErrors).length) {
      setError(labels.why);
      return;
    }

    const result = await authenticateUser(users, username, password);
    onUsersChange(result.users);
    if (result.status === "success" && result.user) {
      finishLogin(result.user, result.users);
      return;
    }
    if (result.status === "mfa_required" && result.user) {
      setPendingUser(result.user);
      setPassword("");
      setMfaCode("");
      setFieldErrors({ mfa: labels.missingMfa });
      setError(labels.mfaRequired);
      return;
    }
    if (result.status === "locked" && result.user) {
      setError(labels.locked.replace("{minutes}", String(lockoutMinutes(result.user))));
      return;
    }
    setError(labels.invalidWithAttempts.replace("{attempts}", String(result.failedAttempts ?? 0)));
  }

  async function submitMfa() {
    if (!pendingUser) return;
    if (!mfaCode.trim()) {
      setFieldErrors({ mfa: labels.missingMfa });
      setError(labels.why);
      return;
    }
    const result = await verifyMfaCode(users, pendingUser.id, mfaCode);
    onUsersChange(result.users);
    if (result.status === "success" && result.user) {
      setPendingUser(null);
      finishLogin(result.user, result.users);
      return;
    }
    if (result.status === "expired") {
      setError(labels.mfaExpired);
      return;
    }
    if (result.status === "locked" && result.user) {
      setError(labels.locked.replace("{minutes}", String(lockoutMinutes(result.user))));
      return;
    }
    setError(labels.invalidMfa);
  }

  async function submitPasswordChange() {
    if (!passwordChangeUser) return;
    if (passwordChangeDraft.next.length < 12) {
      setError(labels.weakPassword);
      return;
    }
    if (passwordChangeDraft.next !== passwordChangeDraft.confirm) {
      setError(labels.mismatch);
      return;
    }
    const passwordHash = await hashPassword(passwordChangeDraft.next);
    const nextUsers = users.map((user) =>
      user.id === passwordChangeUser.id
        ? { ...user, passwordHash, mustChangePassword: false, passwordUpdatedAt: new Date().toISOString() }
        : user
    );
    const nextUser = nextUsers.find((user) => user.id === passwordChangeUser.id);
    onUsersChange(nextUsers);
    setPasswordChangeUser(null);
    setPasswordChangeDraft({ next: "", confirm: "" });
    setError(null);
    if (nextUser) onLogin(nextUser);
  }

  function finishLogin(user: LocalUser, nextUsers: LocalUser[]) {
    onUsersChange(nextUsers);
    if (user.mustChangePassword) {
      setPasswordChangeUser(user);
      setPasswordChangeDraft({ next: "", confirm: "" });
      setPassword("");
      setMfaCode("");
      setError(labels.changeRequired);
      return;
    }
    setError(null);
    setFieldErrors({});
    onLogin(user);
  }

  function resetPasswordStep(value: string) {
    setPassword(value);
    setPendingUser(null);
    setPasswordChangeUser(null);
    setMfaCode("");
    setFieldErrors((current) => ({ ...current, password: undefined, mfa: undefined }));
  }

  const guidance = [fieldErrors.username, fieldErrors.password, fieldErrors.mfa].filter(Boolean) as string[];

  return (
    <main className="login-shell">
      <section className="login-hero">
        <div className="login-brand-mark">
          <ShieldCheck size={30} />
        </div>
        <span>{labels.eyebrow}</span>
        <h1>{labels.title}</h1>
        <p>{labels.subtitle}</p>
        <div className="login-value-grid">
          <div>
            <LockKeyhole size={18} />
            <strong>{labels.model}</strong>
            <span>{labels.posture}</span>
          </div>
          <div>
            <UserRound size={18} />
            <strong>{labels.roles}</strong>
            <span>{labels.governance}</span>
          </div>
        </div>
      </section>

      <section className="login-panel panel">
        <div className="login-panel-tools">
          <div className="login-language-toggle mini-segmented" aria-label={labels.languageTitle}>
            <button type="button" className={language === "es" ? "selected" : ""} onClick={() => onLanguageChange("es")} title="Español">
              ES
            </button>
            <button type="button" className={language === "en" ? "selected" : ""} onClick={() => onLanguageChange("en")} title="English">
              EN
            </button>
          </div>
          <button type="button" className="icon-button" onClick={() => onThemeChange(theme === "dark" ? "light" : "dark")} title={labels.themeTitle}>
            {theme === "dark" ? <Sun size={17} /> : <Moon size={17} />}
          </button>
        </div>
        <form className="login-form" onSubmit={submit}>
          <div>
            <h2>{labels.eyebrow}</h2>
            <p>{language === "es" ? "Sesión local segura para entorno de laboratorio." : "Secure local session for lab operations."}</p>
          </div>
          {sessionMessage ? <div className="session-note">{sessionMessage}</div> : null}
          <label className="field-control">
            <span>{labels.username}</span>
            <input
              value={username}
              onChange={(event) => {
                setUsername(event.target.value);
                setPendingUser(null);
                setFieldErrors((current) => ({ ...current, username: undefined, mfa: undefined }));
              }}
              autoComplete="username"
              aria-label={labels.username}
              aria-invalid={Boolean(fieldErrors.username)}
            />
            {fieldErrors.username ? <small className="field-alert">{fieldErrors.username}</small> : null}
          </label>
          <label className="field-control">
            <span>{labels.password}</span>
            <input
              value={password}
              onChange={(event) => resetPasswordStep(event.target.value)}
              type="password"
              autoComplete="current-password"
              aria-label={labels.password}
              aria-invalid={Boolean(fieldErrors.password)}
            />
            {fieldErrors.password ? <small className="field-alert">{fieldErrors.password}</small> : null}
          </label>
          {pendingUser ? (
            <label className="field-control mfa-control">
              <span>{labels.mfa}</span>
              <input
                value={mfaCode}
                onChange={(event) => {
                  setMfaCode(event.target.value);
                  setFieldErrors((current) => ({ ...current, mfa: undefined }));
                }}
                inputMode="numeric"
                autoComplete="one-time-code"
                aria-label={labels.mfa}
                aria-invalid={Boolean(fieldErrors.mfa)}
              />
              {fieldErrors.mfa ? <small className="field-alert">{fieldErrors.mfa}</small> : null}
            </label>
          ) : null}
          {passwordChangeUser ? (
            <div className="password-change-box login-password-change">
              <div className="security-section-title">
                <LockKeyhole size={17} />
                <div>
                  <strong>{labels.changeRequired}</strong>
                  <span>{labels.weakPassword}</span>
                </div>
              </div>
              <input
                value={passwordChangeDraft.next}
                onChange={(event) => setPasswordChangeDraft({ ...passwordChangeDraft, next: event.target.value })}
                placeholder={labels.newPassword}
                type="password"
                autoComplete="new-password"
              />
              <input
                value={passwordChangeDraft.confirm}
                onChange={(event) => setPasswordChangeDraft({ ...passwordChangeDraft, confirm: event.target.value })}
                placeholder={labels.confirmPassword}
                type="password"
                autoComplete="new-password"
              />
            </div>
          ) : null}
          {guidance.length ? (
            <div className="guided-alert">
              <AlertTriangle size={17} />
              <div>
                <strong>{labels.guidance}</strong>
                <ul>{guidance.map((item) => <li key={item}>{item}</li>)}</ul>
              </div>
            </div>
          ) : null}
          {error ? <div className="error-banner">{error}</div> : null}
          <button className="primary-button" type="submit">
            {pendingUser ? <KeyRound size={17} /> : <LockKeyhole size={17} />}
            <span>{passwordChangeUser ? labels.updateAndEnter : pendingUser ? labels.verify : labels.submit}</span>
          </button>
        </form>
      </section>
    </main>
  );
}
